version: '2'
services:
    registry:
        restart: always
        image: registry:2
        ports:
          - 5000:5000
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
          - /path/data:/var/lib/registry
          - /path/certs:/certs
          - /path/auth:/auth
        labels:
            io.rancher.scheduler.affinity:host_label: server=sub1
            io.rancher.container.hostname_override: container_name
