version: '2'
services:
    registry:
        restart: always
        image: registry:2
        ports:
          - 5000:5000
        environment:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
          - /data:/var/lib/registry          
          - /auth2:/auth
        labels:
            io.rancher.scheduler.affinity:host_label: server=main
            io.rancher.container.hostname_override: container_name

# mkdir auth
# docker run --entrypoint htpasswd registry:2 -Bbn psguest psguest > auth/htpasswd