version: '2'
services:
  nginx:
    image: jlesage/nginx-proxy-manager
    restart: always
    volumes:
      - /docker/appdata/nginx-proxy-manager:/config:rw
    ports:
      - 8080:8181/tcp
      - 8081:8080/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: server=main
      io.rancher.container.hostname_override: container_name
